version: "3.8"
name: planner

services:
  api:
    container_name: api
    build: .
    ports:
      - 3333:3333
    environment:
      # Api
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      API_BASE_URL: ${API_BASE_URL}
      LOG_LEVEL: ${LOG_LEVEL}
      # Web
      WEB_BASE_URL: ${WEB_BASE_URL}
      # Database
      DB_URL: ${DB_URL}
      DB_LOG_LEVEL: ${DB_LOG_LEVEL}
    networks:
      - planner

  postgres:
    container_name: postgres
    image: postgres:16.3-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "planner"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - planner

  postgres-test:
    container_name: postgres-test
    image: postgres:16.3-alpine
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: "planner"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    networks:
      - planner

volumes:
  pg_data:

networks:
  planner:
    driver: bridge
