version: "3.8"
name: planner

services:
  api:
    container_name: planner-api
    build: .
    ports:
      - 3333:3333
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
      WEB_BASE_URL: ${WEB_BASE_URL}
      API_BASE_URL: ${API_BASE_URL}
      PORT: ${PORT}
      LOG_LEVEL: ${LOG_LEVEL}
      DB_LOG_LEVEL: ${DB_LOG_LEVEL}
    networks:
      - planner

  postgres:
    container_name: postgres-db
    image: postgres:16.3-alpine
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - planner

volumes:
  pg_data:

networks:
  planner:
    driver: bridge
