apiVersion: v1
kind: Secret

metadata:
  name: api-vars
type: Opaque

data:
  # Api
  NODE_ENV: cHJvZHVjdGlvbg==
  PORT: MzMzMw==
  API_BASE_URL: aHR0cDovL2xvY2FsaG9zdDozMzMz
  LOG_LEVEL: dHJhY2U=
  # Web
  WEB_BASE_URL: aHR0cDovL2xvY2FsaG9zdDozMDAw
  # Database
  DATABASE_URL: ZmlsZTouL3Byb2QuZGI=
  DB_HOST: DB_HOST
  DB_NAME: DB_NAME
  DB_USER: DB_USER
  DB_PASSWORD: DB_PASSWORD
  DB_PORT: DB_PORT
  DB_LOG_LEVEL: aW5mbw==
