name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: "Build and Push"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate SHA
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Login into the container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image
        run: docker build -t heldercostaa/planner-api:${{ steps.generate_sha.outputs.sha }} .

      - name: Push image
        run: |
          docker push heldercostaa/planner-api:${{ steps.generate_sha.outputs.sha }}
          docker tag heldercostaa/planner-api:${{ steps.generate_sha.outputs.sha }} heldercostaa/planner-api:latest
          docker push heldercostaa/planner-api:latest
