name: CI

on:
  push:
    branches:
      - main

env:
  DATABASE_URL: "file:./test.db"
  WEB_BASE_URL: "http://localhost:3000"
  API_BASE_URL: "http://localhost:3333"
  LOG_LEVEL: "silent"

jobs:
  build-and-push:
    name: "Build and Push"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.15.x"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - uses: codecov/codecov-action@v4
        with:
          file: coverage/tests-report.xml
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Generate SHA
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Log into the container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            heldercostaa/planner-api:${{ steps.generate_sha.outputs.sha }},
            heldercostaa/planner-api:latest
